
x = 10

try:
    print(x)

except:
    print('ERRO')

finally:
    print('Fim do comando')